create database mingzi;
use mingzi;
CREATE TABLE PART (

		P_PARTKEY		FLOAT NOT NULL,
		P_NAME			VARCHAR(55),
		P_MFGR			CHAR(25),
		P_BRAND			CHAR(10),
		P_TYPE			VARCHAR(25),
		P_SIZE			INT(10),
		P_CONTAINER		CHAR(10),
		P_RETAILPRICE	FLOAT,
		P_COMMENT		VARCHAR(23),
		PRIMARY KEY (P_PARTKEY)
	);
CREATE TABLE REGION (
		R_REGIONKEY	FLOAT NOT NULL,
		R_NAME		CHAR(25),
		R_COMMENT	VARCHAR(152),
		PRIMARY KEY (R_REGIONKEY)
);
CREATE TABLE NATION (
		N_NATIONKEY		FLOAT NOT NULL,
		N_NAME			CHAR(25),
		N_REGIONKEY		FLOAT NOT NULL,  -- references R_REGIONKEY
		N_COMMENT		VARCHAR(152),
		PRIMARY KEY (N_NATIONKEY),
		FOREIGN KEY (N_REGIONKEY) REFERENCES REGION(R_REGIONKEY)
);
CREATE TABLE SUPPLIER (
		S_SUPPKEY		FLOAT NOT NULL,
		S_NAME			CHAR(25),
		S_ADDRESS		VARCHAR(40),
		S_NATIONKEY		FLOAT NOT NULL, -- references N_NATIONKEY
		S_PHONE			CHAR(15),
		S_ACCTBAL		FLOAT,
		S_COMMENT		VARCHAR(101),
		PRIMARY KEY (S_SUPPKEY),
		FOREIGN KEY (S_NATIONKEY) REFERENCES NATION(N_NATIONKEY)
);
CREATE TABLE CUSTOMER (
		C_CUSTKEY		FLOAT NOT NULL,
		C_NAME			VARCHAR(25),
		C_ADDRESS		VARCHAR(40),
		C_NATIONKEY		FLOAT NOT NULL, -- references N_NATIONKEY
		C_PHONE			CHAR(15),
		C_ACCTBAL		FLOAT,
		C_MKTSEGMENT	CHAR(10),
		C_COMMENT		VARCHAR(117),
		PRIMARY KEY (C_CUSTKEY),
		FOREIGN KEY (C_NATIONKEY) REFERENCES NATION(N_NATIONKEY)
	);
CREATE TABLE PARTSUPP (
		PS_PARTKEY		FLOAT NOT NULL, -- references P_PARTKEY
		PS_SUPPKEY		FLOAT NOT NULL, -- references S_SUPPKEY
		PS_AVAILQTY		INT(10),
		PS_SUPPLYCOST	FLOAT,
		PS_COMMENT		VARCHAR(199),
		PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY),
		FOREIGN KEY (PS_SUPPKEY) REFERENCES SUPPLIER(S_SUPPKEY),
		FOREIGN KEY (PS_PARTKEY) REFERENCES PART(P_PARTKEY)
);
CREATE TABLE ORDERS (
		O_ORDERKEY		FLOAT NOT NULL,
		O_CUSTKEY		FLOAT NOT NULL, -- references C_CUSTKEY
	O_ORDERSTATUS	CHAR(1),
		O_TOTALPRICE	FLOAT,
		O_ORDERDATE		DATE,
		O_ORDERPRIORITY	CHAR(15),
		O_CLERK			CHAR(15),
		O_SHIPPRIORITY	INT(10),
		O_COMMENT		VARCHAR(79),
		PRIMARY KEY (O_ORDERKEY),
		FOREIGN KEY (O_CUSTKEY) REFERENCES CUSTOMER(C_CUSTKEY)
);
CREATE TABLE LINEITEM (
		L_ORDERKEY		FLOAT NOT NULL, -- references O_ORDERKEY
		L_PARTKEY		FLOAT NOT NULL, -- references P_PARTKEY (compound fk to PARTSUPP)
		L_SUPPKEY		FLOAT NOT NULL, -- references S_SUPPKEY (compound fk to PARTSUPP)
		L_LINENUMBER	INT(10),
		L_QUANTITY		FLOAT,
		L_EXTENDEDPRICE	FLOAT,
		L_DISCOUNT		FLOAT,
		L_TAX			FLOAT,
		L_RETURNFLAG	CHAR(1),
		L_LINESTATUS	CHAR(1),
		L_SHIPDATE		DATE,
		L_COMMITDATE	DATE,
		L_RECEIPTDATE	DATE,
		L_SHIPINSTRUCT	CHAR(25),
		L_SHIPMODE		CHAR(10),
		L_COMMENT		VARCHAR(44),
        PRIMARY KEY (L_ORDERKEY, L_LINENUMBER),
		FOREIGN KEY (L_ORDERKEY) REFERENCES ORDERS(O_ORDERKEY),
		FOREIGN KEY (L_PARTKEY,L_SUPPKEY) REFERENCES PARTSUPP(PS_PARTKEY,PS_SUPPKEY)
	);
