create database mingzi;
use mingzi;
/*CREATE TABLE PART (

		P_PARTKEY		INT(10) NOT NULL,
		P_NAME			VARCHAR(55),
		P_MFGR			CHAR(25),
		P_BRAND			CHAR(10),
		P_TYPE			VARCHAR(25),
		P_SIZE			INT(10),
		P_CONTAINER		CHAR(10),
		P_RETAILPRICE	FLOAT,
		P_COMMENT		VARCHAR(23),
		PRIMARY KEY (P_PARTKEY)
	);*/
CREATE TABLE CUSTOMER (
		C_CUSTKEY		INT(10) NOT NULL,
		C_NAME			VARCHAR(25),
		C_ADDRESS		VARCHAR(40),
		C_NATIONKEY		FLOAT NOT NULL, -- references N_NATIONKEY
		C_PHONE			CHAR(15),
		C_ACCTBAL		FLOAT,
		C_MKTSEGMENT	CHAR(10),
		C_COMMENT		VARCHAR(117),
		PRIMARY KEY (C_CUSTKEY)
	);